### ISSUE TITLE
StackOverflow details stay up?

### ISSUE THREAD

**Issue by kirbyUK** [Phillammon/acrook.co.uk#1]
When you click on the StackOverflow link in the contacts page, then hit back on the browser, the StackOverflow text remains and messes up the display.

![example](https://p.iotek.org/xab.png)

Looks like it happens with the Skype one as well.

**Comment by Phillammon** [comment]
Fault appears to be isolated to the iceweasel browser, and then only when the inspector isn't open. For two buttons only. What the hell.

**Comment by kirbyUK** [comment]
Can confirm it happens in Firefox 45.1.1, and the telephone link is broken as well.

**Comment by Phillammon** [comment]
Fixed!
